version: "3.8"

services:
    timescale:
        image: timescale/timescaledb:latest-pg12
        container_name: timescale
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            # - POSTGRES_DB=${DB_NAME}
        volumes:
            - ./postgresql:/var/lib/postgresql/data
        networks:
            - fmb_network
    
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
            - 5050:80
        depends_on:
            - timescale
        networks:
            - fmb_network

    mongodb:
        container_name: mongodb
        image: mongo:5.0.2
        volumes:
        - ./mongo:/data/db
        ports:
        - "27017:27017"
        environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        # - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        restart: 
            always
        networks:
            - fmb_network

    mongoexpress:
        image: mongo-express
        container_name: mongoexp
        ports:
            - "8081:8081"
        depends_on:
            - mongodb
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}            
            - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN}
            - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
            - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
        networks:
            - fmb_network
    
    neo4j:
        container_name: neo4j
        image: neo4j:4.3.0-enterprise
        restart: always
        volumes: 
            - ./neo4j/data:/data
            - ./neo4j/import:/import
            - ./neo4j/plugins:/plugins
            - ./neo4j/conf:/conf
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
            - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
            - NEO4J_dbms_memory_pagecache_size=8G
            - NEO4j_dbms_memory_heap_initial__size=8G
            - NEO4J_dbms_memory_heap_max__size=16G

networks:
    fmb_network:
        name: fmb_network


        
    